# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='权限名')),
                ('url', models.CharField(max_length=32, verbose_name='带正则的url')),
                ('codes', models.CharField(max_length=32, verbose_name='代码')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Group', verbose_name='所属组')),
                ('menu_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aaa', to='rbac.Permission')),
            ],
            options={
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.RemoveField(
            model_name='perssion',
            name='group',
        ),
        migrations.RemoveField(
            model_name='role',
            name='perssions',
        ),
        migrations.DeleteModel(
            name='Perssion',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='拥有权限的角色'),
        ),
    ]
