# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20171110_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='menu_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aaa', to='rbac.Permission', verbose_name='组内菜单'),
        ),
    ]
